# Generated by Django 5.1.6 on 2025-02-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcheckerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userip',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
