# Generated by Django 5.1.6 on 2025-02-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcheckerapp', '0002_userip_latitude_userip_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
