# Generated by Django 5.1.6 on 2025-02-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcheckerapp', '0003_userip_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='ip_address',
            field=models.GenericIPAddressField(default='192.168.0.0'),
        ),
        migrations.AlterField(
            model_name='userip',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
