# Generated by Django 5.1.6 on 2025-02-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcheckerapp', '0004_userip_is_online_alter_userip_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userip',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
